pyWebFramework/07-flask-lab/01-flask-app/devsynop/main/routes.py
from flask import render_template, request, Blueprint
from devsynop.models import Post

main = Blueprint('main', __name__)


@main.route("/")
# setting up another route
@main.route("/index")
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', posts=posts, title="index") # sending title for frontend


@main.route("/about")
def about():
    return render_template('about.html', title="About")

pyWebFramework/07-flask-lab/01-flask-app/devsynop/stories/routes.py
from flask import (Blueprint, render_template, url_for, flash, 
                    redirect, request, abort)
# flask auth functionality
from flask_login import current_user, login_required

from devsynop import db
from devsynop.models import Post
from devsynop.stories.forms import PostForm

stories = Blueprint('stories', __name__)

@stories.route("/post/create", methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post is created', 'success')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', title="Create Post", form=form, legend="Create post")


@stories.route("/post/<int:post_id>", methods=['GET', 'POST'])
def detail_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('detail_post.html', title=post.title, post=post)


@stories.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post has been updated!', 'success')
        return redirect(url_for('stories.detail_post', post_id=post.id))
    elif request.method == "GET":
        # filling the the form input with database data
        form.title.data = post.title
        form.content.data = post.content 

    return render_template('create_post.html', title="Update Post", form=form, legend="Update post")


@stories.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted!', 'success')
    return redirect(url_for('main.index'))

pyWebFramework/07-flask-lab/01-flask-app/devsynop/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint

from devsynop.users.forms import (RegistrationForm, LoginForm, UpdateProfileForm, 
                   RequestResetForm, ResetPassowrdForm)
from devsynop import db, bcrypt
from devsynop.models import User, Post
# flask auth functionality
from flask_login import login_user, current_user, logout_user, login_required
from devsynop.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        # hashing the password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # setting the data in user table
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        # adding the user in the session
        db.session.add(user)
        # saving the user in database
        db.session.commit()
        flash(f'Your account has been created! Please login to continue', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title="Register", form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    # if already logged in then redirect to index page
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # login using flasklogin extension
            login_user(user, remember=form.remember.data)
            # getting the pattern from url [this will allow us to go to our profile directly if we use the url pattern before logging in.]
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect (url_for('main.index'))
        else:
            flash(f'Login in failed! Please check your email and password again.', 'danger')
    return render_template('login.html', title="Login", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        # updating images
        if form.avatar.data: 
            picture_file = save_picture(form.avatar.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data 
        current_user.email = form.email.data
        db.session.commit()
        flash('Profile information has been updated!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('profile.html', title="Profile", image_file=image_file, form=form)


# user specific posts 
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        #sending token to the email
        send_reset_email(user)
        flash('An email has been sent to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Token has expired', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPassowrdForm()

    if form.validate_on_submit():
        # hashing the password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        # saving the user in database
        db.session.commit()
        flash(f'Your pasword has been updated! Please login to continue', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_token.html', title='Reset Token', form=form)

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/about.html
{% extends "base.html" %}

{% block content %}
<p> A Bangladeshi Online publisher focusing on the stories of techies/developers around the Bangladesh. Join with the community to know more... </p>
{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- Bootstrap CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% if title %}
    <title>DevSynop - {{title}}</title>
    {% else %}
    <title>DevSynop</title>
    {% endif %}
</head>
<body>
    {% include "partials/_navbar.html" %}
    <div class="container my-3">
    <div class="row">

        <div class="col-md-9">
            <!-- display flash message, category="success, danger, or warning" -->
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock %}
        </div>

        <div class="col-md-3 py-lg-3">
            <div class="content-section">
                <h3>Sidebar</h3>
                <p class="text-muted">You can put any information
                <ul class="list-group">
                    <li class="list-group-item">Latest Post</li>
                    <li class="list-group-item">Announcements</li>
                    <li class="list-group-item">Events</li>
                </ul>
                </p>
            </div>
        </div>
        
    </div>
    
    </div>

    
</body>
</html>

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/create_post.html
{% extends "base.html" %}

{% block content %}
<div class="content-section">
    <form action="" method="POST">
        <!-- part of form protection -->
        {{  form.hidden_tag() }} 
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                {{ legend }}
            </legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}

                 <!-- show title error if error present-->
                 {% if form.title.errors %}
                 {{ form.title(class="form-control form-control-lg is-invalid")}}
                 <div class="invalid-feedback">
                     {% for error in form.title.errors %}
                         <span>{{ error }}</span>
                     {% endfor %}
                 </div>
             {% else %}
                 {{ form.title(class="form-control form-control-lg") }}
             {% endif %}
                
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}

                 <!-- show content error -->
                 {% if form.content.errors %}
                 {{ form.content(class="form-control form-control-lg is-invalid")}}
                 <div class="invalid-feedback">
                     {% for error in form.content.errors %}
                         <span>{{ error }}</span>
                     {% endfor %}
                 </div>
             {% else %}
                 {{ form.content(class="form-control form-control-lg") }}
             {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="mt-2 btn btn-sm btn-outline-dark")}}
        </div>
    </form>
</div>

{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/detail_post.html
{% extends "base.html" %}

{% block content %}
<article class="media content-section">
  <img src=" {{ url_for('static', filename='profile_pics/' + post.author.image_file )}} " alt="" class="rounded-circle article-img">
    <div class="media-body">
        <div class="article-metadata">
            <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="mr-2">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>

            {% if post.author == current_user %}
                <div>
                    <a href="{{ url_for('stories.update_post', post_id=post.id) }}" class="btn btn-sm btn-outline-success my-1">Update</a>
                    <button class="btn btn-sm btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{post.title}}</h2>
        <p class="article-content">{{post.content}}</p>
    </div>
</article>


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Story?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
         <form action="{{ url_for('stories.delete_post', post_id=post.id) }}" method="POST">
             <input type="submit" class="btn btn-danger btn-sm" value="Delete">
         </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/index.html
{% extends "base.html" %}

{% block content %}
<section class="text-center container">
    <div class="row py-lg-3">
      <div class="col-md-9 mx-auto">
        <h1 class="fw-light">DevSynop</h1>
        <p class="lead text-muted">The synopsis of deshi devloper stories.</p>
      </div>
    </div>
</section>
{% for post in posts.items %}
<article class="media content-section">
  <img src=" {{ url_for('static', filename='profile_pics/' + post.author.image_file )}} " alt="" class="rounded-circle article-img">
    <div class="media-body">
        <div class="article-metadata">
            <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="mr-2">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a href="{{ url_for('stories.detail_post', post_id=post.id) }}" class="article-title">{{post.title}}</a></h2>
        <p class="article-content">{{post.content}}</p>
    </div>
</article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-3" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-outline-info mb-3" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            <!-- part of form protection -->
            {{  form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Login Here
                </legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                     <!-- show email error if error present-->
                     {% if form.email.errors %}
                     {{ form.email(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.email.errors %}
                             <span>{{ error }}</span>
                         {% endfor %}
                     </div>
                 {% else %}
                     {{ form.email(class="form-control form-control-lg") }}
                 {% endif %}
                    
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                     <!-- show password error -->
                     {% if form.password.errors %}
                     {{ form.password(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.password.errors %}
                             <span>{{ error }}</span>
                         {% endfor %}
                     </div>
                 {% else %}
                     {{ form.password(class="form-control form-control-lg") }}
                 {% endif %}
                    
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="mt-2 btn btn-sm btn-outline-dark")}}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}" class="ml-2">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account? <a href="{{ url_for('users.register') }}" class="ml-2">Sign Up</a>
        </small>
    </div>
{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="content-section">
    <div class="media">
        <img src="{{ image_file }}" alt="" class="rounded-circle account-img">
        <div class="media-body">
            <h3 class="account-heading">{{ current_user.username }}</h3>
            <p>{{ current_user.email }}</p>
        </div>
    </div>
    <!-- Form -->
        <form action="" method="POST" enctype="multipart/form-data">
            <!-- part of form protection -->
            {{  form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Profile Information
                </legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    <!-- show username error -->
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                     <!-- show email error if error present-->
                     {% if form.email.errors %}
                     {{ form.email(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.email.errors %}
                             <span>{{ error }}</span>
                         {% endfor %}
                     </div>
                 {% else %}
                     {{ form.email(class="form-control form-control-lg") }}
                 {% endif %}
                    
                </div>

                <br>
                <div class="form-group">
                    {{ form.avatar.label() }}
                    {{ form.avatar(class="form-control-file") }}
                    {% if form.avatar.errors %}
                        {% for error in form.avatar.errors %}
                             <span class="text-danger">{{ error }}</span>
                             <br>
                         {% endfor %}
                    {% endif %}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="mt-2 btn btn-sm btn-outline-dark")}}
            </div>
        </form>


</div>
{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/register.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            <!-- part of form protection -->
            {{  form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Join Today
                </legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    <!-- show username error -->
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                     <!-- show email error if error present-->
                     {% if form.email.errors %}
                     {{ form.email(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.email.errors %}
                             <span>{{ error }}</span>
                         {% endfor %}
                     </div>
                 {% else %}
                     {{ form.email(class="form-control form-control-lg") }}
                 {% endif %}
                    
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                     <!-- show password error -->
                     {% if form.password.errors %}
                     {{ form.password(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.password.errors %}
                             <span>{{ error }}</span>
                         {% endfor %}
                     </div>
                 {% else %}
                     {{ form.password(class="form-control form-control-lg") }}
                 {% endif %}
                    
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                     <!-- show confirm_password error -->
                     {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="mt-2 btn btn-sm btn-outline-dark")}}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a href="{{ url_for('users.login') }}" class="ml-2">Login</a>
        </small>
    </div>
{% endblock %}

<!-- "b758c33467ca3bd06bb11b2032b5ef3c" secret key -->

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/reset_request.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            <!-- part of form protection -->
            {{  form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Email Address To Change Password
                </legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                     <!-- show email error if error present-->
                     {% if form.email.errors %}
                     {{ form.email(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.email.errors %}
                             <span>{{ error }}</span>
                         {% endfor %}
                     </div>
                 {% else %}
                     {{ form.email(class="form-control form-control-lg") }}
                 {% endif %}                   
               </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="mt-2 btn btn-sm btn-outline-dark")}}
            </div>
        </form>
    </div>
{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/reset_token.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            <!-- part of form protection -->
            {{  form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Reset Password
                </legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                     <!-- show password error -->
                     {% if form.password.errors %}
                     {{ form.password(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.password.errors %}
                             <span>{{ error }}</span>
                         {% endfor %}
                     </div>
                 {% else %}
                     {{ form.password(class="form-control form-control-lg") }}
                 {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                     <!-- show confirm_password error -->
                     {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="mt-2 btn btn-sm btn-outline-dark")}}
            </div>
        </form>
    </div>
{% endblock %}

pyWebFramework/07-flask-lab/01-flask-app/devsynop/templates/user_posts.html
{% extends "base.html" %}

{% block content %}
    <h2 class="mb-3">Stories by {{user.username}} - ({{ posts.total }})</h2>

{% for post in posts.items %}
<article class="media content-section">
  <img src=" {{ url_for('static', filename='profile_pics/' + post.author.image_file )}} " alt="" class="rounded-circle article-img">
    <div class="media-body">
        <div class="article-metadata">
            <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="mr-2">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a href="{{ url_for('stories.detail_post', post_id=post.id) }}" class="article-title">{{post.title}}</a></h2>
        <p class="article-content">{{post.content}}</p>
    </div>
</article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-3" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-outline-info mb-3" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock %}